-- PART - B

CREATE TABLE EMP_DETAIL(
     EMPNO INT,
    EMP_NAME VARCHAR(50),
    JOINDATE DATE,
    SALARY DECIMAL(8,2),
    CITY VARCHAR(20)
);

INSERT INTO EMP_DETAIL VALUES(101,'KEYUR','2002-01-15',12000,'RAJKOT');
INSERT INTO EMP_DETAIL VALUES(102,'HARDIK','2004-02-15',14000,'AHMEDABAD');
INSERT INTO EMP_DETAIL VALUES(103,'KAJAL','2006-03-14',15000,'BARODA');
INSERT INTO EMP_DETAIL VALUES(104,'BHOOMI','2005-06-23',12500,'AHMEDABAD');
INSERT INTO EMP_DETAIL VALUES(105,'HARMIT','2004-02-15',14000,'RAJKOT');
INSERT INTO EMP_DETAIL VALUES(106,'JAY','2007-03-12',12000,'SURAT');

SELECT * FROM EMP_DETAIL;

SELECT JOINDATE , DATEADD(DAY, 365, JOINDATE) FROM EMP_DETAIL;

SELECT FORMAT(JOINDATE, 'MMM d yyyy hh:mmAM/PM') FROM EMP_DETAIL;

SELECT FORMAT(JOINDATE , 'dd MMM yyyy') FROM EMP_DETAIL;

SELECT FORMAT(JOINDATE, 'MMM dd, yy') FROM EMP_DETAIL;

SELECT DATEDIFF(MONTH, JOINDATE, '2009-03-31') FROM EMP_DETAIL;

SELECT DATEDIFF(YEAR, JOINDATE, '2010-09-14') FROM EMP_DETAIL;

-- PART - C

SELECT JOINDATE , DATEPART(DAY,JOINDATE) FROM EMP_DETAIL;
SELECT JOINDATE , DATEPART(MONTH,JOINDATE) FROM EMP_DETAIL;
SELECT JOINDATE , DATEPART(YEAR,JOINDATE) FROM EMP_DETAIL;

SELECT JOINDATE , DATEADD(YEAR , 5 , JOINDATE) FROM EMP_DETAIL;

SELECT JOINDATE , DATEADD(MONTH , -2 , JOINDATE) FROM EMP_DETAIL;

SELECT JOINDATE , DATENAME(MONTH,JOINDATE) FROM EMP_DETAIL;
SELECT JOINDATE , DATEPART(MONTH,JOINDATE) FROM EMP_DETAIL;

-- AGE IN MONTH...
SELECT DATEDIFF(MONTH , '2006-04-16','2024-08-05');
-- AGE IN YEAR...
SELECT DATEDIFF(YEAR , '2006-04-16','2024-08-05');