-- PART - B
SELECT FIRSTNAME , LEN(FIRSTNAME) AS LENGTH_OF_FIRSTNAME , LASTNAME , LEN(LASTNAME) AS LENGTH_OF_LASTNAME FROM STUDENT;

SELECT FIRSTNAME , LOWER(FIRSTNAME) AS LOWER_OF_FIRSTNAME , UPPER(FIRSTNAME) AS UPPER_OF_FIRSTNAME ,
LASTNAME , LOWER(LASTNAME) AS LOWER_OF_LASTNAME , UPPER(LASTNAME) AS UPPER_OF_LASTNAME FROM STUDENT;

SELECT FIRSTNAME , LEFT(FIRSTNAME,3) FROM STUDENT;

SELECT WEBSITE , SUBSTRING(WEBSITE,3,8) FROM STUDENT;

SELECT WEBSITE , LEFT(WEBSITE,4) , RIGHT(WEBSITE,5) FROM STUDENT;

-- PART - C
SELECT FIRSTNAME , SPACE(10) + WEBSITE FROM STUDENT;

SELECT FIRSTNAME +' '+ LASTNAME FROM STUDENT;

SELECT CONCAT(FIRSTNAME,' ',LASTNAME) FROM STUDENT;

SELECT CAST(STUID AS VARCHAR)+' '+FIRSTNAME+' '+LASTNAME+' '+WEBSITE+' '+CITY+' '+ADDRESS FROM STUDENT;

SELECT CONCAT(STUID,' ',FIRSTNAME,' ',LASTNAME,' ',WEBSITE,' ',CITY,' ',ADDRESS) FROM STUDENT;

SELECT FIRSTNAME , REVERSE(FIRSTNAME) FROM STUDENT;

SELECT REPLICATE(FIRSTNAME,3) FROM STUDENT;

SELECT FIRSTNAME FROM STUDENT WHERE LEN(FIRSTNAME) = 5;

SELECT CONCAT(FIRSTNAME,' LIVES IN ',CITY) FROM STUDENT;

SELECT CONCAT('STUDENT_ID OF ',FIRSTNAME,' IS ',STUID) FROM STUDENT;