CREATE TABLE STUDENT_INFO(
    RNO INT,
    FNAME VARCHAR(20),
    BRANCH VARCHAR(20),
    SPI DECIMAL(8,2),
    BKLOG INT
);

INSERT INTO STUDENT_INFO VALUES(101,'RAJU','CE',8.80,0);
INSERT INTO STUDENT_INFO VALUES(102,'AMIT','CE',2.20,3);
INSERT INTO STUDENT_INFO VALUES(103,'SANJAY','ME',1.50,6);
INSERT INTO STUDENT_INFO VALUES(104,'NEHA','EC',7.65,1);
INSERT INTO STUDENT_INFO VALUES(105,'MEERA','EE',5.52,2);
INSERT INTO STUDENT_INFO VALUES(106,'MAHESH','EC',4.50,3);

SELECT * FROM STUDENT_INFO;

CREATE VIEW PERSONAL 
AS SELECT * FROM STUDENT_INFO;

SELECT * FROM PERSONAL;

CREATE VIEW VW_STUDENT_DETAILS 
AS SELECT FNAME,BRANCH,SPI FROM STUDENT_INFO;

SELECT * FROM VW_STUDENT_DETAILS;

CREATE VIEW VW_ACADEMIC_DATA 
AS SELECT RNO,FNAME,BRANCH FROM STUDENT_INFO;

SELECT * FROM VW_ACADEMIC_DATA;

CREATE VIEW VW_STUDENT_BKLOG 
AS SELECT * FROM STUDENT_INFO WHERE BKLOG>2;

SELECT * FROM VW_STUDENT_BKLOG;

CREATE VIEW VW_STUDENT_PATTERN
AS SELECT RNO,FNAME,BRANCH FROM STUDENT_INFO WHERE FNAME LIKE '____';

SELECT * FROM VW_STUDENT_PATTERN;

INSERT INTO VW_ACADEMIC_DATA VALUES(107,'MEET','ME');
SELECT * FROM VW_ACADEMIC_DATA;

UPDATE VW_STUDENT_DETAILS SET BRANCH='ME' WHERE FNAME = 'AMIT';
SELECT * FROM VW_STUDENT_DETAILS;

DELETE FROM VW_ACADEMIC_DATA WHERE RNO=104;