-- PART - B

SELECT COUNT(*) AS NUMOFEMP FROM EMP WHERE CITY = 'RAJKOT';

SELECT MAX(SALARY) - MIN(SALARY) AS DIFFERENCE FROM EMP;

SELECT COUNT(*) AS NUMOFEMP FROM EMP WHERE JOININGDATE < '1991-01-01';

-- PART - C

SELECT COUNT(*) AS NUMOFEMP FROM EMP WHERE CITY IN ('RAJKOT', 'BARODA');

SELECT COUNT(*) AS NUMOFEMP FROM EMP WHERE JOININGDATE < '1991-01-01' AND DEPARTMENT = 'IT';

SELECT JOININGDATE, SUM(SALARY) AS TOTAL_SAL FROM EMP GROUP BY JOININGDATE;

SELECT DEPARTMENT, CITY, MAX(SALARY) AS MAX_SAL FROM EMP WHERE CITY LIKE 'R%' GROUP BY DEPARTMENT, CITY;