CREATE TABLE EMP_DATA(
    EID INT,
    NAME VARCHAR(20)
);

INSERT INTO EMP_DATA VALUES(1,'AJAY');
INSERT INTO EMP_DATA VALUES(9,'HARESH');
INSERT INTO EMP_DATA VALUES(5,'MANISH');

SELECT * FROM EMP_DATA;

CREATE TABLE CUSTOMER_TABLE(
    CID INT, 
    NAME VARCHAR(20)
);

INSERT INTO CUSTOMER_TABLE VALUES(5,'AJAY');
INSERT INTO CUSTOMER_TABLE VALUES(7,'MAHESH');
INSERT INTO CUSTOMER_TABLE VALUES(5,'MANISH');

SELECT * FROM CUSTOMER_TABLE;

DROP TABLE CUSTOMER_TABLE;

-- PART - B
SELECT NAME FROM EMP_DATA
UNION
SELECT NAME FROM CUSTOMER_TABLE;

SELECT NAME FROM EMP_DATA
UNION ALL
SELECT NAME FROM CUSTOMER_TABLE;

SELECT NAME FROM EMP_DATA
INTERSECT
SELECT NAME FROM CUSTOMER_TABLE;

SELECT NAME FROM EMP_DATA
EXCEPT
SELECT NAME FROM CUSTOMER_TABLE;

SELECT NAME FROM CUSTOMER_TABLE
EXCEPT
SELECT NAME FROM EMP_DATA;

-- PART - C
SELECT * FROM EMP_DATA
UNION
SELECT * FROM CUSTOMER_TABLE;

SELECT * FROM EMP_DATA
UNION ALL
SELECT * FROM CUSTOMER_TABLE;

SELECT * FROM EMP_DATA
INTERSECT
SELECT * FROM CUSTOMER_TABLE;

SELECT * FROM EMP_DATA
EXCEPT
SELECT * FROM CUSTOMER_TABLE;

SELECT * FROM CUSTOMER_TABLE
EXCEPT
SELECT * FROM EMP_DATA;