-- PART - B

SELECT REGION,YR,COUNT(PRODUCT) AS TOTAL_PRODUCT FROM SALES_DATA GROUP BY YR,REGION ORDER BY YR,REGION;

SELECT REGION ,MAX(SALES_AMOUNT) AS MAX_AMOUNT FROM SALES_DATA GROUP BY REGION HAVING MAX(SALES_AMOUNT)>1000 ORDER BY REGION;

SELECT YR,SUM(SALES_AMOUNT) AS TOTAL_SAL FROM SALES_DATA GROUP BY YR HAVING SUM(SALES_AMOUNT)<1000 ORDER BY YR DESC;

SELECT TOP 3 REGION,SUM(SALES_AMOUNT) AS TOTAL_SAL FROM SALES_DATA WHERE YR='2024' GROUP BY REGION ORDER BY SUM(SALES_AMOUNT);


-- PART - C

SELECT PRODUCT,AVG(SALES_AMOUNT) AS AVG_AMOUNT FROM SALES_DATA 
GROUP BY PRODUCT HAVING AVG(SALES_AMOUNT)>1000 AND AVG(SALES_AMOUNT)<2000 ORDER BY PRODUCT;

SELECT COUNT(PRODUCT) , REGION FROM SALES_DATA
GROUP BY REGION HAVING COUNT(PRODUCT)>5

SELECT REGION , AVG(SALES_AMOUNT)  FROM SALES_DATA WHERE YR = '2023' 
GROUP BY REGION HAVING AVG(SALES_AMOUNT)>1500
ORDER BY AVG(SALES_AMOUNT) DESC;

SELECT REGION , PRODUCT , COUNT(PRODUCT) FROM SALES_DATA 
GROUP BY REGION , PRODUCT HAVING COUNT(PRODUCT)>1

SELECT REGION, MAX(SALES_AMOUNT) FROM SALES_DATA 
GROUP BY REGION;