SELECT TOP 50 PERCENT * FROM BORROW

SELECT TOP 10 PERCENT AMOUNT FROM DEPOSIT

SELECT TOP 25 PERCENT CNAME FROM DEPOSIT WHERE AMOUNT>5000

SELECT TOP 10 PERCENT AMOUNT FROM BORROW

SELECT DISTINCT CNAME,CITY FROM COUSTMER

select amount,amount+amount*0.10 as new_amount from BORROW

select * from BORROW where LOANNO % 2 != 0

select * from BORROW WHERE LOANNO % 2 = 0

