SELECT * FROM DEPOSIT

SELECT * FROM BORROW

SELECT * FROM CUSTOMER

SELECT ACTNO,CNAME,AMOUNT FROM DEPOSIT

SELECT LOANNO,AMOUNT FROM BORROW

SELECT LOANNO FROM BORROW WHERE BNAME='ANDHERI'

SELECT ACTNO,AMOUNT FROM DEPOSIT WHERE ACTNO=106

SELECT CNAME FROM BORROW WHERE AMOUNT>5000

SELECT CNAME FROM DEPOSIT WHERE ADATE>'1996-12-01'

SELECT CNAME FROM DEPOSIT WHERE ACTNO<105

SELECT CNAME FROM CUSTOMER WHERE CITY='NAGPUR' OR CITY='DEHLI'
SELECT CNAME FROM CUSTOMER WHERE CITY IN('NAGPUR','DELHI') 

SELECT CNAME FROM DEPOSIT WHERE ACTNO<105 AND AMOUNT>4000

SELECT CNAME FROM BORROW WHERE AMOUNT BETWEEN 3000 AND 8000

SELECT CNAME FROM DEPOSIT WHERE BNAME!='ANDHERI'

SELECT ACTNO,CNAME,AMOUNT FROM DEPOSIT WHERE BNAME='AJNI' OR BNAME='KAROLBAGH' OR BNAME='M.G.ROAD' AND ACTNO<104