CREATE TABLE CRICKET(
    NAME VARCHAR(50),
    CITY VARCHAR(50),
    AGE INT
);

INSERT INTO CRICKET VALUES('SACHIN TENDULKAR','MUMBAI',30)
INSERT INTO CRICKET VALUES('RAHUL DRAVID','BOMBAY',35)
INSERT INTO CRICKET VALUES('M.S.DHONI','JHARKHAND',31)
INSERT INTO CRICKET VALUES('SURESH RAINA','GUJARAT',30)

SELECT * FROM CRICKET