CREATE TABLE EMPLOYEE(
    NAME VARCHAR(50),
    CITY VARCHAR(50),
    AGE INT
);

INSERT INTO EMPLOYEE VALUES('JAY PATEL','RAJKOT',30)
INSERT INTO EMPLOYEE VALUES('RAHUL DAVE','BARODA',35)
INSERT INTO EMPLOYEE VALUES('JEET PATEL','SURAT',31)
INSERT INTO EMPLOYEE VALUES('VIJAY RAVAL','RAJKOT',30)

SELECT * FROM EMPLOYEE

SELECT * INTO EMPLOYEE_DETAIL FROM EMPLOYEE

SELECT * FROM EMPLOYEE_DETAIL

SELECT NAME,CITY INTO EMPLOYEE_DATA FROM EMPLOYEE 
WHERE 1=0

SELECT * FROM EMPLOYEE_DATA

SELECT * INTO EMPLOYEE_INFO FROM EMPLOYEE
WHERE 1=0

SELECT * FROM EMPLOYEE_INFO