ALTER TABLE DEPOSIT
ADD CITY VARCHAR(20), PINCODE INT; 

ALTER TABLE DEPOSIT 
ALTER COLUMN CNAME VARCHAR(35);

ALTER TABLE DEPOSIT
ALTER COLUMN AMOUNT INT;

EXEC SP_RENAME 'DEPOSIT.ACTNO','ANO';

ALTER TABLE DEPOSIT
DROP COLUMN CITY;

EXEC SP_RENAME 'DEPOSIT', 'DEPOSIT_DETAIL';

SELECT * FROM DEPOSIT_DETAIL;