DELETE FROM DEPOSIT_DETAIL
WHERE AMOUNT >= 4000;

DELETE FROM DEPOSIT_DETAIL
WHERE BNAME = 'CHANDI BRANCH';

DELETE FROM DEPOSIT_DETAIL
WHERE ANO>105;

TRUNCATE TABLE DEPOSIT_DETAIL;

DROP TABLE DEPOSIT_DETAIL;