CREATE TABLE STUDENT(
    STUID INT,
    FIRSTNAME VARCHAR(25),
    LASTNAME VARCHAR(25),
    WEBSITE VARCHAR(50),
    CITY VARCHAR(25),
    ADDRESS VARCHAR(100)
);



INSERT INTO STUDENT VALUES(1011, 'KEYUR', 'PATEL','techonthenet.com','RAJKOT','A-303 ''vasant kunj'' , Rajkot');
INSERT INTO STUDENT VALUES(1022, 'HARDIK', 'SHAH','digminecraft.com','AHMEDABAD','"Ram Krupa", Raiya Road');
INSERT INTO STUDENT VALUES(1033, 'KAJAL', 'TRIVEDI','bigactivities.com','BARODA','Raj bhavan plot, near
garden');
INSERT INTO STUDENT VALUES(1044, 'BHOOMI', 'GAJERA','checkyourmath.com','AHMEDABAD','"Jig''s Home", Narol');
INSERT INTO STUDENT VALUES(1055, 'HARMIT', 'MITEL','@me.darshan.com','RAJKOT','B-55, Raj Residency');
INSERT INTO STUDENT VALUES(1066, 'ASHOK', 'JANI',NULL,'BARODA','A502, Club House Building');

SELECT * FROM STUDENT;

SELECT FIRSTNAME FROM STUDENT WHERE FIRSTNAME LIKE 'K%';

SELECT FIRSTNAME FROM STUDENT WHERE FIRSTNAME LIKE '_____';

SELECT FIRSTNAME,LASTNAME FROM STUDENT WHERE CITY LIKE '_____A';

SELECT * FROM STUDENT WHERE LASTNAME LIKE '%TEL';

SELECT * FROM STUDENT WHERE FIRSTNAME LIKE 'HA%T'

SELECT * FROM STUDENT WHERE FIRSTNAME LIKE 'K_Y%';

SELECT FIRSTNAME FROM STUDENT WHERE WEBSITE IS NULL AND FIRSTNAME LIKE '_____';

SELECT * FROM STUDENT WHERE LASTNAME LIKE '%JER'

SELECT  * FROM STUDENT WHERE CITY LIKE '[R,B]%';

SELECT * FROM STUDENT WHERE WEBSITE IS NOT NULL;

SELECT * FROM STUDENT WHERE FIRSTNAME LIKE '[A-H]%';

SELECT * FROM  STUDENT WHERE FIRSTNAME LIKE '_[A,E,I,O,U]%';

SELECT * FROM STUDENT WHERE WEBSITE IS NULL AND FIRSTNAME LIKE '%_____%';

SELECT * FROM STUDENT WHERE LASTNAME LIKE 'PAT%';

SELECT * FROM STUDENT WHERE CITY NOT LIKE 'B%';