SELECT * FROM STUDENT WHERE ADDRESS LIKE '%-%';

SELECT * FROM STUDENT WHERE ADDRESS LIKE '%''%' OR ADDRESS LIKE '%"%' ;

SELECT * FROM STUDENT WHERE WEBSITE LIKE '%@%';

SELECT FIRSTNAME FROM STUDENT WHERE LEN(FIRSTNAME) = 4 OR LEN(FIRSTNAME) = 5;