UPDATE DEPOSIT SET AMOUNT=5000 
WHERE AMOUNT = 3000

SELECT * FROM DEPOSIT

UPDATE BORROW  SET BNAME = 'C.G.ROAD'
WHERE CNAME = 'ANIL'

SELECT * FROM BORROW

UPDATE DEPOSIT SET ACTNO=111,AMOUNT=5000
WHERE CNAME='SANDIP'

SELECT * FROM DEPOSIT

UPDATE DEPOSIT SET AMOUNT=7000
WHERE CNAME='KRANTI'

UPDATE BRANCH SET BNAME='ANDHERI WEST'
WHERE BNAME='ANDHERI'

SELECT * FROM BRANCH

UPDATE DEPOSIT SET BNAME='NEHRU PALACE'
WHERE CNAME = 'MEHUL'

UPDATE DEPOSIT SET AMOUNT= 5000
WHERE ACTNO BETWEEN 103 AND 107

SELECT * FROM DEPOSIT


UPDATE DEPOSIT SET ADATE= '1995-04-01'
WHERE CNAME='ANIL'

UPDATE DEPOSIT SET AMOUNT=10000
WHERE CNAME='MINU'

UPDATE DEPOSIT SET AMOUNT=5000,ADATE='1996-04-01' 
WHERE CNAME='PRAMOD' 